# Generated by Django 5.1.15 on 2026-06-11 21:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pipeline', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Amount')),
                ('category', models.CharField(choices=[('ads', 'Advertising'), ('production', 'Production'), ('tools', 'Tools'), ('other', 'Other')], default='ads', max_length=12, verbose_name='Category')),
                ('date', models.DateField(verbose_name='Date')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='pipeline.campaign')),
            ],
            options={
                'verbose_name': 'Expense',
                'verbose_name_plural': 'Expenses',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Revenue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Amount')),
                ('source', models.CharField(blank=True, max_length=120, verbose_name='Source')),
                ('date', models.DateField(verbose_name='Date')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revenues', to='pipeline.campaign')),
            ],
            options={
                'verbose_name': 'Revenue',
                'verbose_name_plural': 'Revenues',
                'ordering': ['-date'],
            },
        ),
    ]
