# Generated by Django 5.1.15 on 2026-06-11 21:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pipeline', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Angle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Name')),
                ('category', models.CharField(choices=[('problem_solution', 'Problem / Solution'), ('benefit', 'Benefit'), ('offer', 'Irresistible Offer')], default='benefit', max_length=32, verbose_name='Category')),
                ('success_rate', models.FloatField(default=0, verbose_name='Success rate (%)')),
            ],
            options={
                'verbose_name': 'Angle',
                'verbose_name_plural': 'Angles',
            },
        ),
        migrations.CreateModel(
            name='Creative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160, verbose_name='Title')),
                ('file', models.FileField(blank=True, null=True, upload_to='creatives/', verbose_name='File')),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], default='image', max_length=8, verbose_name='Type')),
                ('is_winner', models.BooleanField(default=False, verbose_name='Winner?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('angle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creatives', to='assets.angle')),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='creatives', to='pipeline.campaign')),
            ],
            options={
                'verbose_name': 'Creative',
                'verbose_name_plural': 'Creatives',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Hook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Text')),
                ('platform', models.CharField(choices=[('social', 'Social Media'), ('search', 'Search'), ('display', 'Display')], max_length=10, verbose_name='Platform')),
                ('trigger_type', models.CharField(choices=[('curiosity', 'Curiosity'), ('pain', 'Pain Point'), ('demo', 'Demonstration')], max_length=10, verbose_name='Trigger')),
                ('performance_score', models.FloatField(default=0, verbose_name='Performance score')),
                ('angle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hooks', to='assets.angle')),
            ],
            options={
                'verbose_name': 'Hook',
                'verbose_name_plural': 'Hooks',
            },
        ),
    ]
